# Generated by Django 4.2.5 on 2023-10-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_count_user_following_count_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
