# Generated by Django 4.2.5 on 2023-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
