# Generated by Django 4.2.5 on 2023-10-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_posts_time_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unfollow',
            name='follow_status',
        ),
    ]
