# Generated by Django 4.2.5 on 2023-10-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_unfollow_follow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_post', models.TextField(default=None)),
                ('time_post', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='network.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_name_commnet', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
